# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.24
# 

Name:       voicecall

# >> macros
# << macros

Summary:    Voice Call Suite
Version:    0.1.1
Release:    2
Group:      Communications/Telephony and IM
License:    Apache License, Version 2.0
URL:        http://gitorious.org/voicecall-manager
Source0:    %{name}-%{version}.tar.bz2
Requires:   ofono
BuildRequires:  pkgconfig(QtOpenGL)
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(QtMultimediaKit)
BuildRequires:  pkgconfig(libresourceqt1)
BuildRequires:  pkgconfig(libpulse-mainloop-glib)
BuildRequires:  pkgconfig(ofono-qt)

%changelog

%description
Next Generation Dialer Application for Nemo Mobile

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
unset LD_AS_NEEDED
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

%post
/sbin/ldconfig

%postun
/sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_bindir}/voicecall-manager
%{_bindir}/voicecall-ui
%{_libdir}/libvoicecall.so
%{_libdir}/libvoicecall.so.1
%{_libdir}/libvoicecall.so.1.0
%{_libdir}/libvoicecall.so.1.0.0
%{_libdir}/voicecall/plugins/libvoicecall-ofono-plugin.so
%{_libdir}/voicecall/plugins/libvoicecall-pulseaudio-plugin.so
%{_libdir}/voicecall/plugins/libvoicecall-tonegend-plugin.so
%{_datadir}/voicecall-ui/qml
%{_datadir}/applications/voicecall-ui.desktop
%config %{_sysconfdir}/xdg/autostart/voicecall-manager.desktop
%config %{_sysconfdir}/xdg/autostart/voicecall-ui-prestart.desktop
# >> files
# << files

